### ISSUE TITLE
Option to perform custom command with an episode?

### ISSUE THREAD

**Issue by lcabrini** [xgi/castero#100]
Is there a way to do some custom action with an episode. For example, if I'm listenting to a particular episode and decide that I want to open this episode in audacity, can I map a keybinding to this action? That would be really helpful.

**Comment by xgi** [comment]
This doesn't exist, but I can add it. I imagine I would create a config option like "execute_command" which you could set to, i.e. "audacity %s" which would be run if you pressed the 'execute' keybind on an episode.

**Comment by hfel** [comment]
Could also be a useful way to use another audio player in order to take advantage of its features.

**Comment by xgi** [comment]
Added this with #103. Pressing `key_execute` (default e) on an episode will run an arbitrary command. You can set the command with the `execute_command` setting in the config. There is a description above that setting with details about how to use it.

Let me know if you find any issues with this. Thanks!
