### ISSUE TITLE
Unable to import podcasts

### ISSUE THREAD

**Issue by andruyd** [xgi/castero#104]
> Traceback (most recent call last):
>   File "/home/user1/.local/lib/python3.7/site-packages/castero/subscriptions.py", line 54, in load
>     self._tree = ElementTree.parse(path)
>   File "/usr/lib64/python3.7/xml/etree/ElementTree.py", line 1197, in parse
>     tree.parse(source, parser)
>   File "/usr/lib64/python3.7/xml/etree/ElementTree.py", line 587, in parse
>     source = open(source, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: 'Documents/sorted_podcasts_opml.xml'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user1/.local/bin/castero", line 6, in <module>
>     from castero.__main__ import main
>   File "/home/user1/.local/lib/python3.7/site-packages/castero/__main__.py", line 159, in <module>
>     main()
>   File "/home/user1/.local/lib/python3.7/site-packages/castero/__main__.py", line 92, in main
>     import_subscriptions(vars(args)['import'], database)
>   File "/home/user1/.local/lib/python3.7/site-packages/castero/__main__.py", line 25, in import_subscriptions
>     subscriptions.load(path)
>   File "/home/user1/.local/lib/python3.7/site-packages/castero/subscriptions.py", line 57, in load
>     "An I/O exception occurred when attempting to load the file")
> castero.subscriptions.SubscriptionsLoadError: An I/O exception occurred when attempting to load the file

I'm trying to import through an xml file exported from pocketcasts. Before this it would partially work and then cutout with this message. But now it just won't import.

**Comment by xgi** [comment]
Well, from this error it seems that castero isn't finding the 'Documents/sorted_podcasts_opml.xml' file. Are you running castero from a place containing the Documents directory, and are you sure the OPML file exists? Maybe try running the import from inside that directory too, although that shouldn't be necessary.

**Comment by andruyd** [comment]
Thanks and sorry for wasting your time : )
