### ISSUE TITLE
Castero crashes on play

### ISSUE THREAD

**Issue by gvcos** [xgi/castero#108]
Pip3 install castero worked fine.  All libraries installed fine.  MPV player installed and working fine.
Castero import feeds worked fine
All feed show, all episodes show, all metadata shows correctly
download episode works fine, everything seems to work fine except
Enter to play on any episode, downloaded or not, crashes the player without error code.

OS - Pop!_OS 19.10, standard gnome environment.
Tried kitty and gnome terms, same issue.

**Comment by gvcos** [comment]
Resolved - needed to install libmpv1 from Ubuntu repo.

**Comment by andrewfowlie** [comment]
dnf install mpv-devel 

for fedora

**Comment by flobere** [comment]
more specifically, the mpv-libs package is all i needed on fedora.
