### ISSUE TITLE
Better filesystem sandboxing for tests

### ISSUE THREAD

**Issue by nbastin** [xgi/castero#12]
It appears that if you try to test castero with a user that actually has it installed, the tests can't avoid sucking in your user-specific config in some cases, causing failures.  It would be nice if the test harness were fully enclosed and only referred to config files that were stored in the repo or generated on the fly in the tests.

**Comment by xgi** [comment]
I'm not able to reproduce this with the current build, although I have experienced it before. This should be handled already; any test method with the prevent_modification parameter should move the user's config to a .tmp file in the same directory. Is it possible this was caused while you were working on #10?

**Comment by nbastin** [comment]
This has been unfortunately pestering on all my branches, so before #10 for sure.  Some of this seems related the inability to run tests without internet access, but I will have to ponder that separately.

**Comment by xgi** [comment]
Closing since I'm not able to reproduce this -- might be fixed as of a1e52a1439c053fb9d172f311cc57eda8fac911a.

**Comment by tihnessa** [comment]
⚠️ **Critical issue found**

- `EpisodeListMenu.update_items()` uses `hasattr(self._source, "submit_menu_load")` to select the async path. Dynamic/mock query sources report that attribute even though it is not the real loader API, and their mock return value is truthy; the code returns without calling `_load()`, leaving the episode list empty. This regresses the existing menu and terminal behavior (the current suite has six failures). Use a concrete capability/type check or require an explicit async-loader protocol whose method returns a real boolean.

⚠️ GPT-5

**Comment by tihnessa** [comment]
⚠️ Issues found

- `Database.reload` is wrapped in `_serialized`, so its `RLock` is held while `grequests.imap(...)` waits for every network response. Once the worker posts its first `reload` event, `Application.drain_events()` calls `queries.feeds()` and blocks on that lock until the entire refresh finishes. A slow feed therefore freezes the UI and delays all reconciliation—the opposite of the background-reload goal. Limit the lock to actual SQLite reads/writes (or release it before the network phase).

⚠️ GPT-5
