### ISSUE TITLE
Import .opml file doesn't work

### ISSUE THREAD

**Issue by samtay** [xgi/castero#128]
```shell
$ castero --import RadioPublic.opml
Imported 0 feeds
```
There's no parsing error, but it doesn't import anything. you can see the feeds I'm trying to import in [this gist](https://gist.github.com/samtay/87ee4acbb77242e918f0bb587e8290a6). Is this a known issue? Is there any other way to add feeds in bulk?

Current env:
- OS: `MacOS 10.15.5`
- pip -v: `20.0.2` 
- python -v: `3.7`
- castero -V: `0.8.0`
- installation method: `pip3 install castero`

**Comment by xgi** [comment]
Thanks for providing the opml file, I was able to reproduce this and it turned out that the structure was slightly different than what the importer expected. Fixed with #130. thanks!
