### ISSUE TITLE
Basic functionality broken on MacOS 10.15.5

### ISSUE THREAD

**Issue by samtay** [xgi/castero#129]
Added a feed, but pressing space or enter to try to play or enqueue anything just exits without an error message. AFAICT there is no debugging or logging that I can enable? Happy to provide more information.. here's a GIF of what I'm seeing, although I doubt it is helpful:
![screen](https://user-images.githubusercontent.com/7246591/87367855-f5bb0d00-c530-11ea-9e31-0bf4981c9c54.gif)

- **OS**: MacOS 10.15.5
- **Terminal**: Both kitty & native mac Terminal

**Comment by xgi** [comment]
Yeah, sadly I haven't prioritized error logging...

Best guess: do you have either mpv or vlc installed? castero doesn't handle its own playback yet, so you'll need one of them. Make sure you can do either `mpv --version` or `vlc --version`.

**Comment by samtay** [comment]
🤦 Sorry that was right there in your README#dependencies section. I am on a new machine and didn't have `vlc` installed yet. Thank you! Although, I do see helpful messages like [this](https://github.com/xgi/castero/blob/66f1c7c38f1be57abedeb44d269ac3daad7153d0/castero/player.py#L99-L102) in your code; do you consider them not user-friendly enough to print to stderr?

Either way, thank you! App is working great now.

**Comment by xgi** [comment]
No worries, glad it worked out.

And yeah, I'm pretty good about having specific error messages, but curses captures the standard I/O streams so if the client crashes the stacktrace doesn't always get displayed. There are relatively few fatal errors that aren't already handled, but I should probably pipe them to an error.txt log for cases like this :)
