### ISSUE TITLE
Feature request - Default volume option in config file

### ISSUE THREAD

**Issue by ScatteredThoughts** [xgi/castero#140]
Hello,

It would be nice if we could have the volume not set to 100 when castero launches, as that is always too loud, and I immediately have to lower it.

Is this something which could be incorporated in the config file, or as an argument passed when starting castero?

**Comment by xgi** [comment]
Good suggestion, I can add this. Ideally I think we would just have the client remember the last volume, but there's not really an existing structure to save that info. But I can definitely have a config option for the default volume.

**Comment by xgi** [comment]
Added with #143. Thanks!

**Comment by ScatteredThoughts** [comment]
Great! Appreciate the change!
