### ISSUE TITLE
After reload, new items should be marked unplayed

### ISSUE THREAD

**Issue by raniesantos** [xgi/castero#141]
It seems like all new items in the feed are marked played by default.

**Comment by xgi** [comment]
I can do a bit more testing, but I wasn't able to replicate this and I don't see any indication in the code that this would happen.

**Comment by raniesantos** [comment]
Ok the episode I got today was properly marked unplayed.

I'll close this issue when the the next one comes and it shows up correctly.

**Comment by raniesantos** [comment]
It seems this issue only occurs on *some* feeds. Today I reloaded `https://feeds.fireside.fm/linuxunplugged/rss` and got the new episode in a *played* state.

I'll wait for my other feeds to release episodes again to determine which ones have the issue so I can check their xml structure for clues.
