### ISSUE TITLE
Specific feed not working -- Sean Carroll's Mindscape

### ISSUE THREAD

**Issue by whitethief** [xgi/castero#149]
Hello!

Not sure how I can provide more details or check how I can fix this (not much of a py dev myself) but the feed for Sean Carroll's Mindscape does not play the episodes: I can see them being listed with descriptions and everything but the episodes never play. Please let me know if there is something I can do to help debug this.

https://rss.art19.com/sean-carrolls-mindscape
https://www.preposterousuniverse.com/podcast/

**Comment by xgi** [comment]
Sorry, but I just tested this and I wasn't able to reproduce the issue -- the episodes on that feed seem to play fine for me. To clarify, I assume you are able to play episodes from other feeds?

The only potential cause I can think of is that this feed has redirect URLs for episode files; e.g. 118 is listed as 
- `https://dts.podtrac.com/redirect.mp3/chtbl.com/track/9EE2G/pdst.fm/e/rss.art19.com/episodes/5d70d454-01bf-4ebf-82ce-72a723b07830.mp3` which redirects to
- `https://content.production.cdn.art19.com/validation=1602721491,a6cceb0b-d7fc-5b49-aabd-8ed5219906cf,YdFlW01LfNLrw1XFBoPhBND2Jj4/episodes/5d70d454-01bf-4ebf-82ce-72a723b07830/9a0a86e7dcafa51cf18348259c223faf3871acff5e2f0caf80e817344e54e7b5e91e16e1cbe48374a894195c1b9091cd9ff62d2457f53f481278a89956249a4a/adam-riess-complete.mp3`

Presumably the player clients should be able to handle this (they do for me, at least). Maybe this could be an issue at the protocol or system/network level. Sorry, I don't really have any leads.

**Comment by whitethief** [comment]
Hello @xgi,

thanks for answering this, I'll give it another try =).

Regards,
