### ISSUE TITLE
remove background color behind text

### ISSUE THREAD

**Issue by MCWertGaming** [xgi/castero#164]
Currently castero is adding a black background behind the text which doesn't look nice on non-black terminals. It would be cool to be able to completely remove that (with a config / hotkey / arument of whatever). Here is what I mean:

![image](https://user-images.githubusercontent.com/39553804/115432233-aad3d180-a1f5-11eb-9652-935564b03b2b.png)

**Comment by xgi** [comment]
You can set the "color_background" option (in ~/.config/castero/castero.conf) to transparent. Closing since that should be enough, but feel free to re-open if it doesn't work for you.
