### ISSUE TITLE
Loose every progress when checking new episodes

### ISSUE THREAD

**Issue by RaoulSemoule44** [xgi/castero#167]
Hi! Don't know if it's an issue or an upgrade to ask for but I loose every progress in listening episodes when in check for new ones (reloading r/R). As I'm used to listen episodes in several sequences, I would appreciate to keep progress while refreshing the feeds every day. Thanks for your great job!

**Comment by xgi** [comment]
Ah, I think I broke this when I fixed something from being saved when it shouldn't. This should be fixed with #168; I'll increment the version this weekend. Thanks!
