### ISSUE TITLE
[feature request] a 5th layout unifying all feeds

### ISSUE THREAD

**Issue by runrin** [xgi/castero#169]
with the current layouts, it is difficult to know which feeds have new episodes. a view showing episodes from every feed chronologically would be great.

**Comment by xgi** [comment]
I've added this with #170, thanks for the suggestion!

It adds a new perspective which lists episodes from all feeds in chronological order. The only potential concern I have is that it requires loading/displaying all episodes, so it might be slow if you have like tens of thousands across all feeds (it's async so it won't stall or anything, just might take a while to load).

I'll do some profiling to see if I need to add an option to limit the max number to retrieve, but regardless I'll tick the version within 2 weeks.

**Comment by runrin** [comment]
thank you!!
