### ISSUE TITLE
feed fails to add, breaks perspectives 2, 4, and 5

### ISSUE THREAD

**Issue by runrin** [xgi/castero#174]
For some reason, attempting to add this feed `https://mcsorleys.barstoolsports.com/feed/we-gotta-believe` causes castero to exit without properly exiting ncurses.

I was able to add the feed a while ago without any problem, and it remains in my main setup. it does not display properly in any perspective that uses the `[podcast title] episode name` format. It shows as `[We Gotta Believe`

This is probably an issue related to the way the feed is setup, but it does work correctly in the podcast app that I use on my phone.

**Comment by xgi** [comment]
I was able to reproduce this. Might be a few days before I can look into it. Thanks!

**Comment by xgi** [comment]
Sorry for the delay, I've been without a computer. This is fixed with #175 - the issue was that the parsed feed included a newline in the title, which was causing it to try rendering in places it's not allowed to. Thanks!

**Comment by runrin** [comment]
thank you!

**Comment by artamudo** [comment]
Same issue on this link. Latest version.

https://echo.msk.ru/programs/diletanti/rss-audio.xml

Please try to fix it.

**Comment by xgi** [comment]
@artamudo This was fixed in #176, please see my comment there.

**Comment by artamudo** [comment]
> @artamudo This was fixed in #176, please see my comment there.

Sorry, I have to delete that comment. I already use castero from git, and this works pretty nice.
