### ISSUE TITLE
Do not clear queue when manually playing next episode

### ISSUE THREAD

**Issue by llucps** [xgi/castero#180]
Hi,

First of all, thank you for such a great project.

I have a little bit of trouble with the queue behavior though.

The thing is if I add for example 3 episodes in the queue and start playing the first one, if I manually navigate to the second episode and hit "return" to start playing it, then the previous episode is removed from thew queue.

I couldn't find though a way to avoid removing those episodes from the queue. Is there way to do that?

Thanks.

**Comment by xgi** [comment]
You can skip to the next episode in the queue by pressing `n` (can change as key_next in the config). This will keep the rest of the queue intact. Alternatively, you can go to the "queue perspective" by pressing 2, which will show the list of episodes in the queue, with the currently playing one at the top. If you press `enter` on an episode in that list, it will jump to it and remove the previous episodes from the queue (the subsequent ones will remain).

Let me know if that didn't address your comments. Thanks!

**Comment by llucps** [comment]
Thanks @xgi ,

Although it works as you say, I find that weird honestly. I would presume that I could play any episode in the queue without "removing" any of the previous ones.

If I have 10 episodes in the queue I think I should be able to play the number 5 episode in the list without removing the 1-4 ones.

Only episodes that are "finished" should be removed from the list, and ideally have a hotkey to clear out all the episodes in the list in one go.

Does make sense what I say?

Thanks!

**Comment by xgi** [comment]
Yeah, I get what you're saying. imo though, that would be more akin to a playlist than a queue. The decision to have a queue instead was deliberate to make some aspects more straightforward, but it lacks the persistence like you describe.

I can understand the use-cases from your side, but I'm not sure I'm able to commit to changing this behavior for now -- it would take a fairly significant functional rework.

**Comment by llucps** [comment]
I understand, no problem. I was asking in case it was something doable and easy.

Thanks!
