### ISSUE TITLE
Handle current episode url with script to enable copy to clipboard

### ISSUE THREAD

**Issue by plum** [xgi/castero#185]
Hi, thanks for a great podcast cli.
I do like the feature of show current url, and so I wonder, because i do share episodes frequently, if and how I may get a handle on the current episode url in Castero,  with script to enable copy to clipboard?
John

**Comment by xgi** [comment]
You can use the `execute_command` for this. There's a description in the template config: https://github.com/xgi/castero/blob/master/castero/templates/castero.conf#L50-L63

You can set it to something like `execute_command = ~/copyurl.sh {link}` where `copyurl.sh` is some script that takes the link from the first parameter. Then in castero just press `e` to run the script with the selected episode (or change `key_execute`).

Let me know if this doesn't work for you, thanks!

**Comment by plum** [comment]
Thanks, I see now.

Running on wayland, I got it to work with the simple command in castero.conf:
`execute_command = wl-copy {link}`

None of the following rials worked:
```
#execute_command = '"{link}" | wl-copy'
#execute_command = 'wl-copy < {link}'
#execute_command = 'wl-copy "{link}"' 
#execute_command = 'wl-copy {link}'
```
Thanks kindly, It's great.
