### ISSUE TITLE
New release request (with width fix)

### ISSUE THREAD

**Issue by frozencemetery** [xgi/castero#191]
Hi, 48cdfdef7feec7d4cfe5935e1484709703f6ed99 ("fix crash when opening help with very thin window") went in back in October, but there hasn't been a release since then.  Normally I'd just run from git, but devices with narrow screens are the hardest to do that on :)

Any chance of a release for that bugfix?  Thanks!

**Comment by xgi** [comment]
Sure, I've published 0.9.5. Thanks!
