### ISSUE TITLE
Support speed increase over 2.0x

### ISSUE THREAD

**Issue by Kenneth-Mata** [xgi/castero#192]
please up the maximum speed increase from 2.0x to 3.0x .

**Comment by ScriptForAll** [comment]
I can work on this issue since I've made this change already in my machine.
This is a simple change in the queue.py, in the variable MAX_VELOCITY.


However, I'm new to GitHub coding-wise so I don't know how to commit this change to this repository. :sweat_smile:

**Comment by adamm-xyz** [comment]
This seems like a good first issue and should have that label attached. @xgi Thoughts? It is hacktoberfest after all as well.
