### ISSUE TITLE
Feature Request: autoplay queue

### ISSUE THREAD

**Issue by Glog78** [xgi/castero#199]
It would be amazing if we could have a autoplay feature for the internal player and for the internal queue. Even it's only configurable in the config file.

**Comment by Glog78** [comment]
oh it is already implemented , not sure why it didn't work earlier.

**Comment by elXaptation** [comment]
My recent install of castero is not autoplaying in the queue. Does it need to be enabled in config.. I didn't see it in the default config file. How do I get autoplay to work? Thank you.

  castero help
  ============

  Version: 0.9.5
  Updated: 2022-04-02
  Maintainer: xgi <xgi@faltro.com>
  License: MIT License
  URL: https://github.com/xgi/castero
