### ISSUE TITLE
[Feature Request]: Add MPRIS Support For Linux Users

### ISSUE THREAD

**Issue by ethanmassie** [xgi/castero#203]
Implementing the [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/) API will provide multimedia control support to castero (i.e bluetooth headphone controls, keyboard controls, applets like kde media player etc.).  

It looks like this can be implemented with the [mpris-server](https://pypi.org/project/mpris-server/) python package.

**Comment by KiaraGrouwstra** [comment]
this seems a duplicate of #110
