### ISSUE TITLE
VLC no longer seems to work

### ISSUE THREAD

**Issue by nbastin** [xgi/castero#21]
Surprisingly, castero changes your config automatically to default to mpv from vlc (probably would have been smoother to leave existing configs as vlc).

However, even after you change it to VLC, you still get:
```castero.player.PlayerDependencyError: Sufficient dependencies were not met for any players```

I haven't really looked into yet, so I'm not sure if there's anything obvious here.

**Comment by xgi** [comment]
Should be fixed, thanks for the heads up. It would probably be good to have an installation check in the CI build to catch these kinds of oversights.
