### ISSUE TITLE
error adding rss feed

### ISSUE THREAD

**Issue by laherre** [xgi/castero#27]
I get an error with the following feed:

https://fitnessrevolucionario.com/feed/podcast/
An error ocurred while downloading the feed
(I attach the current xml for the rss)

Really don't know how to debug the error, or if it's and issue...

PD-  Sorry my english, and thanx by the software.
Attach: [fitnessrev-rss-xml.txt](https://github.com/xgi/castero/files/2875074/fitnessrev-rss-xml.txt)

**Comment by xgi** [comment]
Should be resolved, thanks for the link!

**Comment by laherre** [comment]
solved! 

Thanx
