### ISSUE TITLE
Install issue - missing 'perspectives' directory

### ISSUE THREAD

**Issue by kmac** [xgi/castero#3]
I'm installing this via archlinux PKGBUILD, which does a fairly simple `python setup.py install --root="$pkgdir/" --optimize=1` (see https://aur.archlinux.org/packages/castero-git/).

The issue that I'm seeing is that the 'perspectives' directory doesn't get created under the installation directory, which causes castero to bomb as soon as a key is pressed. 

Looking through your setup.py - is it possible you need to add the 'perspectives' directory to the package_data, i.e. here?:

````
    package_data={
        'castero': ['templates/*'],
},
````

**Comment by xgi** [comment]
Thanks for the heads up, this should be fixed with 29a5e479108829293b72cf545a22f6e9824d65bb.
