### ISSUE TITLE
feature request: played status

### ISSUE THREAD

**Issue by prankousky** [xgi/castero#31]
Hi,

I am currently subscribed to 47 feeds with 5919 total episodes. I love using castero on my laptop to listen to these podcasts, but not being able to see which episodes have already been played makes it difficult sometimes.

Especially because I just started really getting into castero, but have already listened to hundreds of these episode.

So I was wondering if there will be a feature in the future that will mark unplayed/played status (or perhaps an option to toggle displaying all episodes or unplayed only, or perhaps both option combined)?

Thanks in advance.

**Comment by xgi** [comment]
Yes, this is planned!

I'm currently working on an overall of the storage system, which will allow for this kind of dynamic metadata (among other things). Played status was one of the first things I wanted to implement, so it should be supported soon.
