### ISSUE TITLE
Queue reset when client is closed

### ISSUE THREAD

**Issue by taziden** [xgi/castero#37]
Hi,

I've noticed the queue has been emptied after I accidentally exited castero. I had carefully selected episodes to listen, and was surprised to find the queue empty after launching again castero.

I think it would make sense to automatically save the queue and have it restored at startup.
What do you think?

**Comment by xgi** [comment]
Seems reasonable to me. I was initially concerned about performance, but it would probably be sufficient to export the queue when the client is (safely) exited.

Thanks! (and sorry)

**Comment by xgi** [comment]
Added with 23a14fb7d9eecffe3c59d5af09e047de63624988. Let me know if there are any issues. Thanks!

**Comment by taziden** [comment]
Thanks for the quick and positive answer. i'll test it right away :)
