### ISSUE TITLE
feature request: playback speed

### ISSUE THREAD

**Issue by trailjeep** [xgi/castero#38]
I know in MPV  <kbd>[</kbd> & <kbd>]</kbd> can be used to adjust playback speed, would it be possible to add this feature?

**Comment by xgi** [comment]
Should be possible! I'll add that sometime this week -- I'll also need to check whether any other functionality may break if the playback speed is distorted, but I don't think that will be a problem.

**Comment by xgi** [comment]
Added, let me know if there are any issues.

Thanks!

**Comment by trailjeep** [comment]
Works great - thank you!
P.S. It always makes me happy when I can fully replace GUI apps with terminal ones!
