### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by trailjeep** [xgi/castero#39]
In `castero.conf` it should be clarified that `custom_download_dir` is relative to home directory.
I tried `~/Podcasts` & `$HOME/Podcasts` which respectively created `/home/USER/~/Podcasts` and `/home/USER/$HOME/Podcasts`.

ex.
```
[downloads]
# The location to save episodes downloaded for offline playback. Set to blank
# or whitespaces to disable -- the client will default to either $XDG_DATA_DIR,
# if set, otherwise ~/.local/share/castero/downloaded
# Note: this is relative to your home directory - to use ~/Podcasts set to Podcasts.
# default: (blank)
custom_download_dir = 
```

**Comment by xgi** [comment]
I actually wasn't aware the path was relative so I'll actually change the functionality to use an absolute path instead (that was the intention). I'll add a specific note of that as well, though.
