### ISSUE TITLE
Crashes when feed item lacks audio

### ISSUE THREAD

**Issue by loetus** [xgi/castero#52]
Hello,

First, thanks for working on this app, I love the simple interface!

My problem is that if there happens to be a "news item" in a feed that contains no audio file, the application will crash.

For instance I listed to Software Engineering Radio. There are a few items that come up in their feed like this:

[https://www.se-radio.net/2018/03/seeking-a-new-volunteer-host/](https://www.se-radio.net/2018/03/seeking-a-new-volunteer-host/)

Attempting to download this "episode" will cause a crash. Here is a sample paste of some of the output. It is hard to grab all of it as the errors scroll:

[https://is.gd/dBtmWK](https://is.gd/dBtmWK)

Let me know if I can provide any more info.

Cheers

**Comment by xgi** [comment]
I was able to reproduce this, thanks for the report. imo it makes the most sense to simply not include an item in castero's listing if it has no media content. So I'll get that done in a bit.

Theoretically I could just fix this issue by checking if there is valid content before playing/downloading the episode... but I don't want people to start using castero as their news feed.

**Comment by xgi** [comment]
Added the functionality described above with #53. You'll need to reload the feed with `r`.

Also fixed the crashing issue for the general case of a bad URL with #54.

Thanks!
