### ISSUE TITLE
Feature Request: OPML Import

### ISSUE THREAD

**Issue by josh-clarke** [xgi/castero#55]
I have  a lot of podcasts in a different app which would be nice to import _en masse_. I wonder if OPML import (and maybe export) could be implemented?

**Comment by xgi** [comment]
This should be possible; you can do `castero -h` to see the relevant commands (there is currently no way to do this inside the client). It hasn't been extensively tested though, so let me know if you find any issues.

I think this is resolved, but I'll leave it open until I add this info to the readme. Thanks!
