### ISSUE TITLE
Support 16 terminal colors (i.e. bright color variants)

### ISSUE THREAD

**Issue by rien333** [xgi/castero#60]
I'm pretty sure there is more colors available in a color theme than just "black, blue, cyan, green, magenta, red, white, yellow". For example, [cmus](https://github.com/cmus/cmus/wiki/Themes) (which is  also curses-based) supports bright variants of said colors, e.g. light-yellow.  I think most themes I've seen also define 16 colors (see e.g. [nord](https://github.com/arcticicestudio/nord)). The  fix for this seems pretty simple (just add more names to `COLOR_NAMES` in https://github.com/xgi/castero/blob/master/castero/display.py), so I might make a PR if I dig castero (just discovered it).  EDIT:  used it for a bit, great app, just what I needed.

**Comment by xgi** [comment]
Well, the client does technically support 16 colors. It's just that the bold variants are applied under specific cases (like for menu headers, or for section headings in the metadata window). I do understand the desire to manually use an 8-15 color, though.

One solution would be to separate the config options for normal text and header text, and add support for specifying any of the 16 colors. The default header-text config option would then be `bold-yellow`, for example. I might do that, but I'm sure it would be a bit annoying for people who want them to be the same base color (which I assume is the vast majority).

However, what I think I'll do is add support for specifying a bold variant (whether with `bold-*` or just supporting color numbers) which would then simply be matching with the heading text.

**Comment by xgi** [comment]
curses doesn't actually include any other named colors, so I'm inclined to not define them arbitrarily. Making use of them is still supported, though, with the color number (0-255, or 0-15 for 16 bit). Personally, I think using the number makes more sense in general, because for the client `yellow` just means `3` which has no actual guarantee of being yellow, depending on the terminal color scheme.

**Comment by rien333** [comment]
Silly me, wasn't aware that the range 0-15 was reserved for those colors. Thanks!!
