### ISSUE TITLE
Stricter separation of color configuration options

### ISSUE THREAD

**Issue by rien333** [xgi/castero#61]
Now, the color of the header and the footer is the same as the color of a selected item. Conceptually, these do not seem like the same thing, and although I've found a color I'm satisfied with for the selected item, it makes the header and footer unreadable (see screenshot below). 

Other color options should have less global effects too/be more user specifiable too, imo, but I'm not sure if you're open for more changes. In [cmus](https://cmus.github.io/), which is very similar  looking, you have separate color options for the headers and the dividing lines, and the color of the main text. I kinda dig this, because this gives headers a visual style of being important, but keeps the text my preferred color, so that `castero` doesn't look out of style. 
![2019-11-11-1573485284](https://user-images.githubusercontent.com/10417027/68598077-64296600-049e-11ea-8b71-174a233ee5b6.jpg)

**Comment by xgi** [comment]
Sure, this seems reasonable. I'll need to look into this a bit more, but I think I'll add the following options:
```
color_foreground_status (for the header and footer bars)
color_foreground_heading (for menu headings, i.e. Feeds, Episodes, Metadata)
color_foreground_dividers
```
I don't think I'll add any additional background color options for these; they'll just use the same setting as for the other text.

Thanks!

**Comment by rien333** [comment]
Yeah, those three options seem to cover all necessary stuff. Thanks for your work, and sorry for all my issues.
