### ISSUE TITLE
Not save Play position

### ISSUE THREAD

**Issue by Monirzadeh** [xgi/castero#63]
when i play an episode and than play another episode or exit from program
castero don't save play position and start from the start 
i don't know that is bug or castero not support that for now?
it is so important for long episode.
can you please add this feature to castero?

**Comment by rien333** [comment]
`mpv` allow you to resume playback, so it definitely is theoretically possible.

**Comment by Monirzadeh** [comment]
it can be use but if castro can save that separately it can be use for sync with gpodder playback position.
`mpv -ss time episode.mp3`
read the position of episode from a file slow down the program?

**Comment by silvernode** [comment]
It would be nice to have a hotkey like Ctrl+s that saves the sate on a given file so that the timestamp is marked for resuming later.

**Comment by hfel** [comment]
I tried setting `mpv --save-position-on-quit` as the player in the config, but that had no impact; all episodes still started from the beginning.

**Comment by robincafolla** [comment]
+1 on this. The playlist resuming when you reopen castero would be a phenomenal addition (it's a feature I've installed half a dozen players looking for and haven't found)
