### ISSUE TITLE
Error: (IndexError: list index out of range) when going to next episode in queue

### ISSUE THREAD

**Issue by caltlgin** [xgi/castero#70]
Steps to reproduce:
1. Add 2 or more episodes to queue.
2. Go to queue view and highlight another entry other than the first entry.
3. Press the n key to start playing the next episode in the queue until until you get the error when the selected entry is at the bottom of the queue.

Error occurs only when selected episode is not the first entry in the queue.

**Comment by xgi** [comment]
Just adding that I was able to reproduce this. Thanks!

**Comment by xgi** [comment]
Fixed with #74. Thanks!
