### ISSUE TITLE
Error: [Segmentation fault (core dumped)] when pressing the Enter key twice in queue view

### ISSUE THREAD

**Issue by caltlgin** [xgi/castero#71]
**Steps to reproduce:**
1. Add episodes to queue.
2. Start playing episode with Enter key.
3. Press enter key again to get the segmentation fault.

*Version: 0.6.0 PyPi*

**Comment by xgi** [comment]
I was able to reproduce this. Thanks!

**Comment by xgi** [comment]
Fixed with #73. Thanks!
