### ISSUE TITLE
Feature request: Show number of (unplayed) episodes of each feed in feed list

### ISSUE THREAD

**Issue by Brn9hrd7** [xgi/castero#77]
I think there should be an option to show the number of unplayed episodes, and maybe also the total number of episodes for each feed in the feed list.

**Comment by xgi** [comment]
This seems useful. I could add a (#unplayed/#total) counter somewhere. I can add an option to have it in the menu headers, like `Episodes (14/52)`. Thanks!

**Comment by xgi** [comment]
Added with #81. Thanks!
