### ISSUE TITLE
macOS stderr symbol not found

### ISSUE THREAD

**Issue by d3ddd** [xgi/castero#82]
After downloading castero for the first time (using pip), if I try to open castero I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/castero", line 5, in <module>
    from castero.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/castero/__main__.py", line 142, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/castero/__main__.py", line 109, in main
    temp_file = redirect_stderr()
  File "/usr/local/lib/python3.7/site-packages/castero/__main__.py", line 51, in redirect_stderr
    c_stderr = ctypes.c_void_p.in_dll(libc, 'stderr')
ValueError: dlsym(RTLD_DEFAULT, stderr): symbol not found

I've done a fairly thorough search to  attempt to solve this with no success. I'm assuming it's mac specific?

**Comment by xgi** [comment]
Yeah, that was definitely a Mac thing (the OS uses a different name for one of the file descriptors). Should be fixed with #83 but I don't have a Mac to test, so let me know if it isn't.

Thanks!

**Comment by d3ddd** [comment]
Thanks, it's working great. I installed Castero manually to get this fix and I'm wondering if I should be reinstalling it with pip at some point? Sorry if that's a bit of a newb question.

**Comment by xgi** [comment]
Glad it worked! This fix will be part of the next update, but that probably won't be for a few weeks so running the manual build is totally fine. pip will still recognize that you have castero installed so whenever it gets updated you can use pip to update the usual way (`pip install --upgrade castero`). Right now it would just say there are no updates. Configs and local data are shared so you don't have to worry about that getting overwritten either.
