### ISSUE TITLE
Laggy UI during reload?

### ISSUE THREAD

**Issue by lcabrini** [xgi/castero#99]
Sometimes I experience the UI to be really laggy. I noticed it shortly after hitting 'r', so I assume maybe it was because of the reload? But wouldn't the reload/update happen in a separate process? Or could it be the player that was causing it?

One thing I really like about gPodder is that it uses and external player: mpv and vlc both already have queues, so gPodder can focus on just being a podcatcher without trying to also be a media player. Can I get this with castero as well?

**Comment by xgi** [comment]
Yes, there are some existing performance concerns. I'll close this since I think it's already covered with another issue, #92.
